List
victoriafomina/Homework-Semester-2- pull request #5
Opened 2019-03-15 22:31 UTC by victoriafomina

I implemented the list class that can add, pop and get an element from the position set by integer number.

2019-04-02 09:30 UTC, yurii-litvinov requested changes
Вообще всё ок, но надо немного подправить

2019-04-02 09:30 UTC, yurii-litvinov commented on hw2/List/List/List.cs
> +        }
Это лучше `private int Size => size`

2019-04-02 09:30 UTC, yurii-litvinov commented on hw2/List/List/List.cs
> +          => size == 0;
Отступы же 4 пробела обычно

2019-04-02 09:30 UTC, yurii-litvinov commented on hw2/List/List/List.cs
> +            else
else не нужен, там же return

2019-04-02 09:30 UTC, yurii-litvinov commented on hw2/List/List/List.cs
> +        private class Node<T2>
Node правильнее не иметь свой параметр-тип, а получить его из объемлющего класса. T2 не может отличаться от T1 ведь

2019-04-02 09:30 UTC, yurii-litvinov commented on hw2/List/List/List.cs
> +    /// <typeparam name="T1"></typeparam>
Пустые комментарии не нужны --- либо удалите вообще, либо напишите что-нибудь :)

2019-04-02 09:30 UTC, yurii-litvinov commented on hw2/List/List/List.cs
> +                };
Можно без temp, и лучше сделать Node конструктор, чем применять тут инициализатор

2019-04-02 09:30 UTC, yurii-litvinov commented on hw2/List/List/List.cs
> +                throw new ArgumentOutOfRangeException(string.Format("Invalid position", position,
Вместо string.Format тут лучше $"...{position}..."

2019-04-02 09:30 UTC, yurii-litvinov commented on hw2/List/List/desktop.ini
> +List.cs=@List.cs,0
Думаю, что этот файл не надо

2019-04-14 22:59 UTC, victoriafomina commented on hw2/List/List/List.cs
> +        }
Мне же нужно иметь private setter и public getter. Не поняла вас

2019-04-18 09:38 UTC, victoriafomina commented on hw2/List/List/List.cs
> +        private class Node<T2>
Исправила, но теперь вылезает ворнинг, если собрать проект.

2019-04-19 18:52 UTC, victoriafomina commented on hw2/List/List/List.cs
> +        private class Node<T2>
А нет, все окей

2019-05-02 07:57 UTC, yurii-litvinov approved these changes
Окей, зачтена

2019-05-02 07:57 UTC, yurii-litvinov commented on hw2/List/List.Tests/ClassDiagram1.cd
> +﻿<?xml version="1.0" encoding="utf-8"?>
Это не надо :)

2019-05-02 07:57 UTC, yurii-litvinov commented on hw2/List/List.Tests/List.Tests.csproj
> +  <Target Name="EnsureNuGetPackageBuildImports" BeforeTargets="PrepareForBuild">
Из-за этого AppVeyor не собирает, лучше удалит этот тэг Target вообще, со всеми его сыновьями

2019-05-02 07:57 UTC, yurii-litvinov commented on hw2/List/List/List.cs
> +        /// <exception cref="ArgumentOutOfRangeException"Thrown when position is invalid.></exception>
Тут что-то с `>` не так

2021-05-15 17:35 UTC, merged